# Generated by Django 6.0.7 on 2026-08-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_savedjob_remove_application_unique_job_applicant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(default='India', max_length=80),
        ),
    ]
